services:
  # ---- Le bot Discord ----
  - type: worker
    name: bot-discord
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: ""
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OWNER_IDS
        sync: false

  # ---- Le dashboard web ----
  - type: web
    name: bot-dashboard
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci
    startCommand: npm run web
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: SITE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
